# Generated by Django 5.2.1 on 2025-05-26 03:24

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('image', models.ImageField(upload_to='homepage/', verbose_name='Титульные картинки')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ['-created_at'],
            },
        ),
    ]
