# Generated by Django 5.2.1 on 2025-05-17 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(db_index=True, max_length=30, verbose_name='Название статьи')),
                ('title_img', models.ImageField(upload_to='legends/title_img/', verbose_name='Титульное изображение')),
                ('title_description', models.CharField(max_length=50, verbose_name='Описание')),
                ('tag_color', models.CharField(default='#000000', max_length=7, verbose_name='Tag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликовать')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Легенда',
                'verbose_name_plural': 'Легенды',
                'ordering': ['-created_at'],
            },
        ),
    ]
