# Generated by Django 5.2.1 on 2025-05-17 17:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Содержание'),
        ),
    ]
