<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-18 08:48
=======
# Generated by Django 5.2.1 on 2025-05-18 09:50
>>>>>>> wonders

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legends', '0002_legend_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='legends/audio/', verbose_name='Аудиофайл'),
        ),
    ]
