# Generated by Django 5.2.1 on 2025-05-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wonder',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='wonders/audio/', verbose_name='Аудиофайл'),
        ),
    ]
